version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:latest"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-myuser}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-mypassword}
    ports:
      - "5672:5672"
      - "15672:15672"
    # volumes:
    #   - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - mynetwork
    cpuset: '2'

  # timescaledb:
  #   image: timescale/timescaledb:latest-pg13
  #   container_name: my_timescaledb
  #   environment:
  #     POSTGRES_DB: gateio
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - timescaledb_data:/var/lib/postgresql/data
  #   networks:
  #     - mynetwork

  # gateio-api:
  #   build:
  #     context: ./gateio_api
  #   environment:
  #     - WS_URL=ws://gateio-ws:3000
  #     - RABBITMQ_URL=amqp://myuser:mypassword@rabbitmq:5672
  #     - INFLUXDB_URL=http://influxdb:8086
  #     - INFLUXDB_DATABASE=your_database_name
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - influxdb
  #     - rabbitmq
  #     - timescaledb
  #   networks:
  #     - mynetwork

  # gateio-ws:
  #   build:
  #     context: ./gateio_ws
  #   environment:
  #     - API_URL=ws://gateio-api:3000
  #     - RABBITMQ_URL=amqp://myuser:mypassword@rabbitmq:5672
  #     - INFLUXDB_URL=http://influxdb:8086
  #     - INFLUXDB_DATABASE=your_database_name
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - influxdb
  #     - rabbitmq
  #     - timescaledb
  #   networks:
  #     - mynetwork

  consumer:
    build:
      context: ./consumer
    # environment:
      # - API_URL=ws://gateio-api:3000
      # - RABBITMQ_URL=amqp://myuser:mypassword@rabbitmq:5672
      # - INFLUXDB_URL=http://influxdb:8086
      # - INFLUXDB_DATABASE=your_database_name
      # - TZ=Asia/Yerevan
    ports:
      - "3033:3033"
    # depends_on:
    #   - rabbitmq
      # - timescaledb
    networks:
      - mynetwork
    cpuset: '0'

  producer:
    build:
      context: ./producer
    # environment:
      # - API_URL=ws://gateio-api:3000
      # - RABBITMQ_URL=amqp://myuser:mypassword@rabbitmq:5672
      # - INFLUXDB_URL=http://influxdb:8086
      # - INFLUXDB_DATABASE=your_database_name
      # - TZ=Asia/Yerevan
    ports:
      - "3333:3333"
    # depends_on:
    #   - rabbitmq
      # - timescaledb
    networks:
      - mynetwork
    cpuset: '0'

  # influxdb:
  #   build:
  #     context: ./influxdb
  #   environment:
  #     INFLUXDB_DB: ${INFLUXDB_DB:-gateio}
  #     INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER:-admin}
  #     INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD:-admin_password}
  #     INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD:-user_password}
  #     INFLUXDB_USER: ${INFLUXDB_USER:-user}
  #   ports:
  #     - "8086:8086"
  #   volumes:
  #     - influxdb-data:/var/lib/influxdb

# volumes:
#   rabbitmq-data:
  # timescaledb_data:
  # influxdb-data:

networks:
  mynetwork:
    driver: bridge
