version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg12
    environment:
      - POSTGRES_DB=gateio
      - POSTGRES_USER=open
      - POSTGRES_PASSWORD=interest
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
  gateio-ws:
    build:
      context: ./gateio_ws
    environment:
      - TIMESCALE_DB=gateio
    ports:
      - "3003:3003"
    networks:
      - mynetwork
    # volumes:
    # - ws_data:/usr/src/app

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=your_password
      - REDIS_REQUIREPASS=another_password
    volumes:
      - redis-data:/data
    networks:
      - mynetwork

  gateio-api:
    build:
      context: ./gateio_api
    ports:
      - "3001:3001"
    networks:
      - mynetwork
    # volumes:
    #   - api_data:/usr/src/app

  coinalyze:
    build:
      context: ./coinalyze
    ports:
      - "8008:8008"
    networks:
      - mynetwork
    environment:
      - POSTGRES_DB=coinalyze
      - POSTGRES_USER=open
      - POSTGRES_PASSWORD=interest
    volumes:
      - coinalyze_data:/usr/src/app


volumes:
  redis-data:
  timescaledb_data:
  coinalyze_data:
  # ws_data:
  # api_data:
  # cronjob_data:

networks:
  mynetwork:
    driver: bridge
  network1:
    driver: bridge
  network2:
    driver: bridge
  network3:
    driver: bridge

  # cron:
  #   build:
  #     context: ./cronjobs
  #   volumes:
  #     - cronjob_data:/usr/src/app
