version: '3'

services:
  rabbitmq:
    build:
      context: ./message_broker
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-myuser}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-mypassword}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  influxdb:
    build:
      context: ./database
    environment:
      INFLUXDB_DB: ${INFLUXDB_DB:-mydatabase}
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER:-admin}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD:-admin_password}
      INFLUXDB_USER: ${INFLUXDB_USER:-user}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD:-user_password}
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb

  gateio-api:
    build:
      context: ./gateio_api
    environment:
      - WS_URL=ws://gateio-ws:3000
      - RABBITMQ_URL=amqp://myuser:mypassword@rabbitmq:5672
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_DATABASE=your_database_name
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
      - rabbitmq

  gateio-ws:
    build:
      context: ./gateio_ws
    environment:
      - API_URL=ws://gateio-api:3000
      - RABBITMQ_URL=amqp://myuser:mypassword@rabbitmq:5672
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_DATABASE=your_database_name
    ports:
      - "3001:3001"
    depends_on:
      - influxdb
      - rabbitmq

volumes:
  rabbitmq-data:
  influxdb-data:
