# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
# --no-cache-dir
RUN pip install -r requirements.txt 
# Make port 80 available to the world outside this container
# EXPOSE 3030

# Define environment variable
ENV TZ=Asia/Yerevan

# Run app.py when the container launches
CMD ["python", "consum.py"]
# CMD ["python", "rabbitRecivmsg.py"]
