# Use the official Node.js LTS image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install -g typescript
RUN npm install
# Copy the rest of the application code
COPY . .

# Build TypeScript code
RUN npm run build

# Expose the port your app will run on
EXPOSE 3000

# Command to run the application
CMD [ "npm", "start" ]