# Use the official InfluxDB image from Docker Hub
FROM influxdb:latest

# Expose the default InfluxDB port
EXPOSE 8086

# Set environment variables for InfluxDB configuration
ENV INFLUXDB_DB=gateiodb
ENV INFLUXDB_HTTP_AUTH_ENABLED=true
ENV INFLUXDB_ADMIN_USER=admin
ENV INFLUXDB_ADMIN_PASSWORD=admin_password
ENV INFLUXDB_USER=user
ENV INFLUXDB_USER_PASSWORD=user_password

# Optionally, set other configuration parameters if needed
# ENV INFLUXDB_HTTP_AUTH_ENABLED=true
# ENV INFLUXDB_RETENTION_POLICY=myretentionpolicy
# ...

# Define the volume for InfluxDB data persistence
VOLUME /var/lib/influxdb